# Generated by Django 4.1.2 on 2022-10-22 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='register',
            name='Mobile',
        ),
        migrations.RemoveField(
            model_name='register',
            name='Password',
        ),
    ]
