# Generated by Django 4.1.2 on 2022-10-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_registeruser_alter_usermaster_is_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='Otp',
            field=models.IntegerField(default=True),
        ),
    ]
