# Generated by Django 4.1 on 2022-10-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_postuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postuser',
            name='img',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
