# Generated by Django 4.1.2 on 2022-10-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_postuser_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postuser',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='registeruser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='postuser',
            name='user_id',
            field=models.ManyToManyField(to='app.usermaster'),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='user_id',
            field=models.ManyToManyField(to='app.usermaster'),
        ),
    ]
