# Generated by Django 4.1 on 2022-10-27 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_postuser_user_id_remove_registeruser_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postuser',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='registeruser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='postuser',
            name='user_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app.usermaster'),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.usermaster'),
            preserve_default=False,
        ),
    ]
