# Generated by Django 4.1.2 on 2022-11-01 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='postuser',
            name='Email',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.usermaster'),
            preserve_default=False,
        ),
    ]
