# Generated by Django 4.1.2 on 2022-11-01 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_postuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postuser',
            name='Email',
        ),
    ]
